apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-dogbot
spec:
  replicas: 1
  selector:
    matchLabels:
      name: discord-dogbot
  template:
    metadata:
      labels:
        name: discord-dogbot
    spec:
      containers:
      - name: discord-dogbot
        image: ghcr.io/totegamma/discord-dogbot:master
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: dogbot-secrets
        livenessProbe:
          exec:
            command:
              - rm
              - /tmp/healthy
          initialDelaySeconds: 30
          periodSeconds: 120
